sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  webhooks: https://hubot-mill.herokuapp.com/hubot/travis?room=angular-translate
  on_start: true
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release
branches:
  only:
    - master
