sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  webhooks: https://hubot-mill.herokuapp.com/hubot/travis?room=angular-translate
  on_start: true
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
  - npm install -g grunt-cli
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
